require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RoundtablesController do

  # This should return the minimal set of attributes required to create a valid
  # Roundtable. As you add validations to Roundtable, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RoundtablesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all roundtables as @roundtables" do
      roundtable = Roundtable.create! valid_attributes
      get :index, {}, valid_session
      assigns(:roundtables).should eq([roundtable])
    end
  end

  describe "GET show" do
    it "assigns the requested roundtable as @roundtable" do
      roundtable = Roundtable.create! valid_attributes
      get :show, {:id => roundtable.to_param}, valid_session
      assigns(:roundtable).should eq(roundtable)
    end
  end

  describe "GET new" do
    it "assigns a new roundtable as @roundtable" do
      get :new, {}, valid_session
      assigns(:roundtable).should be_a_new(Roundtable)
    end
  end

  describe "GET edit" do
    it "assigns the requested roundtable as @roundtable" do
      roundtable = Roundtable.create! valid_attributes
      get :edit, {:id => roundtable.to_param}, valid_session
      assigns(:roundtable).should eq(roundtable)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Roundtable" do
        expect {
          post :create, {:roundtable => valid_attributes}, valid_session
        }.to change(Roundtable, :count).by(1)
      end

      it "assigns a newly created roundtable as @roundtable" do
        post :create, {:roundtable => valid_attributes}, valid_session
        assigns(:roundtable).should be_a(Roundtable)
        assigns(:roundtable).should be_persisted
      end

      it "redirects to the created roundtable" do
        post :create, {:roundtable => valid_attributes}, valid_session
        response.should redirect_to(Roundtable.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved roundtable as @roundtable" do
        # Trigger the behavior that occurs when invalid params are submitted
        Roundtable.any_instance.stub(:save).and_return(false)
        post :create, {:roundtable => {}}, valid_session
        assigns(:roundtable).should be_a_new(Roundtable)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Roundtable.any_instance.stub(:save).and_return(false)
        post :create, {:roundtable => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested roundtable" do
        roundtable = Roundtable.create! valid_attributes
        # Assuming there are no other roundtables in the database, this
        # specifies that the Roundtable created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Roundtable.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => roundtable.to_param, :roundtable => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested roundtable as @roundtable" do
        roundtable = Roundtable.create! valid_attributes
        put :update, {:id => roundtable.to_param, :roundtable => valid_attributes}, valid_session
        assigns(:roundtable).should eq(roundtable)
      end

      it "redirects to the roundtable" do
        roundtable = Roundtable.create! valid_attributes
        put :update, {:id => roundtable.to_param, :roundtable => valid_attributes}, valid_session
        response.should redirect_to(roundtable)
      end
    end

    describe "with invalid params" do
      it "assigns the roundtable as @roundtable" do
        roundtable = Roundtable.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Roundtable.any_instance.stub(:save).and_return(false)
        put :update, {:id => roundtable.to_param, :roundtable => {}}, valid_session
        assigns(:roundtable).should eq(roundtable)
      end

      it "re-renders the 'edit' template" do
        roundtable = Roundtable.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Roundtable.any_instance.stub(:save).and_return(false)
        put :update, {:id => roundtable.to_param, :roundtable => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested roundtable" do
      roundtable = Roundtable.create! valid_attributes
      expect {
        delete :destroy, {:id => roundtable.to_param}, valid_session
      }.to change(Roundtable, :count).by(-1)
    end

    it "redirects to the roundtables list" do
      roundtable = Roundtable.create! valid_attributes
      delete :destroy, {:id => roundtable.to_param}, valid_session
      response.should redirect_to(roundtables_url)
    end
  end

end
